# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(max_length=32, verbose_name='\u5bf9\u5e94\u5206\u533a')),
                ('disk_type', models.CharField(max_length=32, verbose_name='\u786c\u76d8\u7c7b\u578b')),
                ('disk_size', models.CharField(max_length=32, verbose_name='\u786c\u76d8\u5927\u5c0f')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('cpu', models.CharField(max_length=32, verbose_name='CPU')),
                ('memory', models.CharField(max_length=32, verbose_name='\u5185\u5b58')),
                ('os', models.CharField(default='CentOS', max_length=32, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('status', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5728\u7ebf')),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_info', models.CharField(max_length=64, verbose_name='CPU\u4fe1\u606f')),
                ('kernelrelease', models.CharField(max_length=32, verbose_name='\u5185\u6838\u540d\u79f0')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('serialnumber', models.CharField(max_length=128, verbose_name='\u5e8f\u5217\u53f7')),
                ('minion_version', models.CharField(max_length=16, verbose_name='Minion\u7248\u672c')),
                ('osrelease', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saltstack.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=32, verbose_name='IP\u5730\u5740')),
                ('network_name', models.CharField(max_length=32, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('mac_addr', models.CharField(max_length=32, verbose_name='MAC\u5730\u5740')),
                ('bandwidth', models.CharField(blank=True, max_length=10000, null=True, verbose_name='\u5e26\u5bbd')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u673a\u623f/\u5730\u533a')),
                ('principal', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('cabinet', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u673a\u67dc\u4f4d\u7f6e')),
                ('room_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saltstack.HostInfo')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='hostinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.HostInfo'),
        ),
    ]
