# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u673a\u623f/\u5730\u533a')),
                ('principal', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('cabinet', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u673a\u67dc\u4f4d\u7f6e')),
            ],
        ),
        migrations.RemoveField(
            model_name='network',
            name='region',
        ),
    ]
