# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0002_permission_role_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u542b\u6b63\u5219\u7684URL'),
        ),
    ]
