# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0002_auto_20181003_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_info',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, to='saltstack.HostInfo'),
            preserve_default=False,
        ),
    ]
