# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0003_room_room_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saltstack.HostInfo'),
        ),
    ]
