# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0004_auto_20181009_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='saltstack.Permission'),
        ),
    ]
